exclude: '^$'
fail_fast: false
default_language_version:
    python: python3.9
repos:
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            args:
              --max-line-length=120
              --extend-ignore=E1,W1,E2,W2,E3,W3,E4,W4,E5,W5
            language_version: python3.9
    - repo: https://github.com/ambv/black
      rev: 22.3.0
      hooks:
          - id: black
            args: [--line-length=120, --target-version=py39]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: check-symlinks
          - id: check-ast
          - id: check-merge-conflict
          - id: debug-statements
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.942
      hooks:
          - id: mypy
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.8.0.4
      hooks:
          - id: shellcheck
